# Generated by Django 2.2.6 on 2019-11-26 17:19

import classes.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PhClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_age', models.IntegerField(unique=True, validators=[classes.validators.validate_age])),
                ('max_age', models.IntegerField(unique=True, validators=[classes.validators.validate_age])),
                ('facilitator', models.CharField(blank=True, max_length=200)),
            ],
        ),
    ]
