# Generated by Django 2.2.6 on 2020-01-19 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PhClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ageGroup', models.CharField(max_length=30)),
                ('class_designation', models.CharField(default='CLASS A', max_length=64)),
                ('name', models.CharField(default='N/A', max_length=64)),
                ('min_age', models.IntegerField(default=3)),
                ('max_age', models.IntegerField(default=6)),
            ],
        ),
    ]
