# Generated by Django 2.2.6 on 2019-11-26 17:19

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=64)),
                ('middle_name', models.CharField(max_length=64, null=True)),
                ('last_name', models.CharField(max_length=64)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('neighbourhood', models.CharField(max_length=64)),
                ('primary_phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='KE')),
                ('secondary_phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, null=True, region='KE')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Child',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=64)),
                ('middle_name', models.CharField(max_length=64, null=True)),
                ('last_name', models.CharField(max_length=64)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dob', models.DateField(verbose_name='Date Of Birth')),
                ('is_active', models.BooleanField(default=True)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='children', related_query_name='child', to='children.Parent')),
                ('ph_class', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', related_query_name='child', to='classes.PhClass', verbose_name='Project Heritage Class')),
            ],
            options={
                'verbose_name_plural': 'Children',
                'abstract': False,
            },
        ),
    ]
